services:

  dagster-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  # dagster-daemon:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: "dagster-daemon run"